// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7aPHW-2Vul6HKN4l4zmCgDUKf5h-pxo',
    appId: '1:390420502621:web:9e04bc726a16e6fb1695b4',
    messagingSenderId: '390420502621',
    projectId: 'fcis-guide',
    authDomain: 'fcis-guide.firebaseapp.com',
    storageBucket: 'fcis-guide.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpnplYFklr-aRwvtfRj-SFNjV-jldzZPM',
    appId: '1:390420502621:android:23d4902e8e5739151695b4',
    messagingSenderId: '390420502621',
    projectId: 'fcis-guide',
    storageBucket: 'fcis-guide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhvh50pw-efAmqV-4nn50EDqwqy2xtN1w',
    appId: '1:390420502621:ios:83363a80b4caa6b81695b4',
    messagingSenderId: '390420502621',
    projectId: 'fcis-guide',
    storageBucket: 'fcis-guide.appspot.com',
    iosBundleId: 'com.example.fcisGuide',
  );
}
